export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const SHOW_COMPANY = 'SHOW_COMPANY';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const SHOW_EMPLOYEE = 'SHOW_EMPLOYEE';